- name: Ensure summon lib directory exists
  file:
    dest: /usr/local/lib/summon
    state: directory
    mode: 0755
- name: Add gopass for summon
  tags: [golang, goenv, gopass]
  become: true
  copy:
    src: gopasspwd
    dest: /usr/local/lib/summon/gopass
    mode: 0755
- name: Ensure zsh is installed
  tags: [zsh]
  apt:
    name: zsh
- name: Set shell to zsh
  tags: [zsh]
  user:
    name: "{{ user.name }}"
    append: true
    shell: /usr/bin/zsh
- name: Install browserpass-native
  tags: [browserpass]
  make:
    target: "{{ item }}"
    chdir: "{{ user.home }}/go/src/github.com/browserpass/browserpass-native"
  with_items:
    - install
    - hosts-firefox
- name: Install logrotate config for xsession-errors
  tags: [xsession]
  copy:
    src: xsession-errors
    dest: /etc/logrotate.d/
    mode: 0644
