# vim: set foldmethod=marker nospell:
---
- name: Install Greenhouse root CA # {{{
  tags: [ca]
  get_url:
    url: https://s3.amazonaws.com/grnhse-vpc-assets/certs/greenhouse-root-ca.pem
    dest: /usr/local/share/ca-certificates/greenhouse-root-ca.crt
    owner: root
    group: root
    mode: 0644
    force: true
# }}}
- name: Update CA Certificates # {{{
  tags: [ca]
  command: update-ca-certificates
  # }}}
- name: Install aws-vault # {{{
  tags: [aws]
  get_url:
    url: "https://github.com/99designs/aws-vault/releases/download/v{{ aws_vault.version }}/aws-vault-linux-amd64"
    dest: /usr/local/bin/aws-vault
    owner: root
    group: root
    mode: 0755
    force: true
# }}}
- name: Install 1password cli # {{{
  tags: [1password]
  unarchive:
    src: https://cache.agilebits.com/dist/1P/op/pkg/{{ op.version }}/op_linux_amd64_{{ op.version }}.zip
    dest: /usr/local/bin
    remote_src: true
    owner: root
    group: root
    mode: 0755
# }}}
# {{{ Install teleport
- name: Create teleport install dir
  tags: [k8s, teleport]
  file: path=/tmp/teleport state=directory

- name: Install teleport
  tags: [k8s, teleport]
  unarchive:
    src: https://get.gravitational.com/teleport-{{ teleport.version }}-linux-amd64-bin.tar.gz
    dest: /tmp/
    remote_src: true
    owner: root
    group: root
    mode: 0755

- name: Install teleport
  tags: [k8s, teleport]
  copy:
    src: /tmp/teleport/tsh
    dest: /usr/local/bin/tsh
    owner: root
    group: root
    mode: 0755

- name: Remove teleport installation files
  tags: [k8s, teleport]
  file:
    path: /tmp/teleport
    state: absent
# }}}
# Install duoconnect {{{
- name: Create install dir
  tags: [duoconnect]
  file: path=/tmp/duoconnect state=directory

- name: Install duoconnect
  tags: [duoconnect]
  unarchive:
    src: https://dl.duosecurity.com/DuoConnect-latest.tar.gz
    dest: /tmp/duoconnect/
    remote_src: true
    owner: root
    group: root

- name: Install duoconnect
  tags: [duoconnect]
  copy:
    src: /tmp/duoconnect/duoconnect
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755

- name: Remove duoconnect installation files
  tags: [duoconnect]
  file:
    path: /tmp/duoconnect
    state: absent
# }}}
# {{{ Install go-jira
- name: Install go-jira
  tags: [jira]
  become: true
  become_user: root
  get_url:
    url: https://github.com/go-jira/jira/releases/download/{{ gojira.version }}/jira-linux-amd64
    dest: /usr/local/bin/jira
    mode: 0755
    force: true
# }}}
# Install dive {{{
- name: Set dive url
  tags: [dive]
  set_fact:
    dive_url: https://github.com/wagoodman/dive/releases/download/v{{ dive.version }}/dive_{{ dive.version }}_linux_amd64.tar.gz

- name: Create dive install dir
  tags: [dive]
  file: path=/tmp/dive state=directory

- name: Download dive
  tags: [dive]
  get_url:
    url: "{{ dive_url }}"
    dest: /tmp/dive

- name: Unpack dive
  tags: [dive]
  shell: |
    tar -zxpf *.tar.gz
  args:
    chdir: /tmp/dive

- name: Install dive
  tags: [dive]
  copy:
    src: /tmp/dive/dive
    remote_src: true
    dest: /usr/local/bin/dive
    owner: root
    group: root
    mode: 0755

- name: Remove dive installation files
  tags: [dive]
  file:
    path: /tmp/dive
    state: absent
# }}}
