---
- name: Provision a new computer
  hosts: all, localhost
  gather_facts: yes

  vars:
    user:
      name: jcmuller
      group: jcmuller
      home: /home/jcmuller
    ubuntu:
      release: cosmic

  pre_tasks:
    - name: What is this?
      tags: pre_tasks
      debug:
        msg: "{{ ansible_distribution }}"

    - name: Update all packages
      tags: pre_tasks
      apt:
        upgrade: dist
        update_cache: yes
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Update all packages
      tags: pre_tasks
      pacman:
        upgrade: yes
        update_cache: yes
      become: true
      when: ansible_distribution == 'Archlinux'

    - name: Create user
      user:
        name: "{{ user.name }}"
        groups: sudo
        append: true
        shell: /usr/bin/zsh
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Create user
      user:
        name: "{{ user.name }}"
        append: true
        shell: /usr/bin/zsh
      become: true
      when: ansible_distribution == 'Archlinux'

  roles:
    - role: desktop/base
      tags: [base]
      become: true

    - role: desktop/user
      tags: [user]

    - role: desktop/alacritty
      tags: [alacritty]

    - role: desktop/neovim
      tags: [neovim]

    - role: desktop/iptables
      tags: [iptables]
      become: true

    - role: desktop/work
      tags: [work]
      become: true

  post_tasks:
    - name: Add {{ user.name }} to docker group
      tags: docker
      user:
        name: "{{ user.name }}"
        groups: docker
        append: true
      become: true
