---
docker_compose:
  version: 1.25.4

docker_engine:
  version: 19*
  ubuntu_release: bionic

docker_machine:
  version: 0.16.0

jq:
  version: "1.6"

plantuml:
  version: 1.2020.2

slack:
  version: 4.4.0

slackcat:
  version: "1.6"

nextcloud:
  version: 2.6.4

yj:
  version: v4.0.0

yq:
  version: 3.1.2
