- name: Ensure summon lib directory exists
  file:
    dest: /usr/local/lib/summon
    state: directory
- name: link gopass for summon
  tags: [golang, goenv]
  become: true
  file:
    src: "/home/{{ user.name }}/go/bin/gopass"
    dest: /usr/local/lib/summon/gopass
    state: link
- name: Ensure zsh is installed
  tags: [zsh]
  apt:
    name: zsh
- name: Set shell to zsh
  tags: [zsh]
  user:
    name: "{{ user.name }}"
    append: true
    shell: /usr/bin/zsh
- name: Install browserpass-native
  tags: [browserpass]
  make:
    target: "{{ item }}"
    chdir: "{{ user.home }}/go/src/github.com/browserpass/browserpass-native"
  with_items:
    - install
    - hosts-firefox
