---
- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: Install paru using makepkg if it isn't installed already
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present

- name: Update all packages including AUR
  become_user: aur_builder
  kewlfft.aur.aur:
    upgrade: true

- name: Install packages includin AUR
  tags: aur
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{arch.packages}}"

- name: Enable and restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog.service
    enabled: true
    state: restarted
    daemon_reload: true
