# vim: set foldmethod=marker nospell:
---
- name: Download alacritty # {{{
  git:
    repo: https://github.com/alacritty/alacritty.git
    dest: ~/Development/OSS/alacritty
    version: "v{{ alacritty.version }}"
# }}}
- name: Build alacritty # {{{
  args:
    executable: /bin/bash
    chdir: ~/Development/OSS/alacritty
  shell: |
    source ~/.asdf/asdf.sh
    git config --global --unset-all url.git@github.com:.insteadOf
    cargo install cargo-deb
    cargo deb --install -p alacritty
    git config --global --add url.git@github.com:.insteadOf gh:
    git config --global --add url.git@github.com:.insteadOf https://github.com/
# }}}
- name: Install binary # {{{
  become: true
  apt:
    deb: "~/Development/OSS/alacritty/target/debian/alacritty_{{ alacritty.version }}_amd64.deb"
# }}}
- name: Install logo # {{{
  become: true
  copy:
    src:  ~/Development/OSS/alacritty/extra/logo/alacritty-term.svg
    dest: /usr/share/pixmaps/Alacritty.svg
    owner: root
    group: root
    mode: 0755
# }}}
- name: Install desktop entry # {{{
  become: true
  args:
    executable: /bin/bash
    chdir: "~{{user.name}}/Development/OSS/alacritty"
  shell: |
    desktop-file-install extra/linux/Alacritty.desktop
    update-desktop-database
# }}}
- name: Install alternative # {{{
  become: true
  args:
    executable: /bin/bash
    chdir: "~{{user.name}}/Development/OSS/alacritty"
  shell: update-alternatives --install /usr/bin/x-terminal-emulator
      x-terminal-emulator /usr/local/bin/alacritty 100

# }}}
