# vim: set foldmethod=marker nospell:
---
- name: Install packages
  tags: [packages, core]
  apt:
    name:
      - apt-transport-https
      - awscli
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - dunst
      - gettext # neovim
      - git
      - gnupg2
      - gnutls-bin
      - graphviz
      - htop
      - laptop-mode-tools
      - ldap-utils
      - libtool-bin # neovim
      - libpq-dev
      - libssl-dev # required for older version of ruby
      - libreadline-dev
      - moreutils
      - neomutt
      - openssh-server
      - openvpn
      - pass
      - pass-extension-tail
      - pkg-config
      - phantomjs
      - postgresql-client
      - powerline
      - powertop
      - py3status
      - python-boto
      - python-dev
      - python-pip
      - python3-pip
      - python-virtualenv
      - qrencode
      - redis-tools
      - redshift-gtk
      - rofi
      - shellcheck
      - sloccount
      - socat
      - tmux
      - tree
      - traceroute
      - xclip
      - zsh
    state: latest
    update_cache: true

- name: Install ruby build dependencies
  tags: [ruby, packages]
  apt:
    name:
      - libgmp-dev
      - libreadline-dev
      - libsqlite3-dev
      - zlib1g-dev
    state: latest

- name: Install desktop packages
  tags: [packages, desktop]
  apt:
    name:
      - arandr
      - gimp
      - firefox
      - i3
      - i3lock-fancy
      - maim
      - xfonts-terminus
    state: latest

- name: Add powerline symbols to terminus font
  tags: [packages, powerline]
  copy:
    src: 11-powerline-symbols-terminus.conf
    dest: /etc/fonts/conf.d/
    owner: root
    group: root
    mode: 0644

- name: Install slack client
  tags: [packages, desktop, slack]
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack.version }}-amd64.deb"
    state: present

- name: Install spotify
  tags: [packages, desktop, spotify]
  command: sudo snap install spotify

- name: Add apt keys for docker
  tags: [packages, docker]
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository for docker
  tags: [packages, docker]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ docker_engine.ubuntu_release }} stable"
    state: present
    update_cache: yes

- name: Install docker
  tags: [packages, docker]
  apt:
    pkg: docker-ce
    state: present

- name: Install docker-compose
  tags: [packages, docker, docker-compose]
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: Install docker-machine
  tags: [packages, docker, docker-machine]
  get_url:
    url: "https://github.com/docker/machine/releases/download/v{{ docker_machine.version }}/docker-machine-Linux-x86_64"
    dest: /usr/local/bin/docker-machine
    owner: root
    group: root
    mode: 0755

- name: Add apt keys for gcloud
  tags: [packages, gcloud]
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add apt repository for gcloud
  tags: [packages, gcloud]
  apt_repository:
    repo: deb http://packages.cloud.google.com/apt cloud-sdk-{{ ubuntu.release }} main
    state: present
    update_cache: true

- name: Install gcloud
  tags: [packages, gcloud]
  apt:
    pkg: google-cloud-sdk
    state: present

- name: Add sudoers files
  tags: [sudoers]
  copy:
    src: sudoers.d/
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: 0440
    validate: "visudo -cf %s"

- name: Modify nsswitch.conf
  tags: [nsswitch]
  copy:
    src: nsswitch.conf
    dest: /etc/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Install heroku toolbelt
  tags: [heroku]
  shell: wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

- name: Install Slackcat
  tags: [slackcat]
  get_url:
    url: "https://github.com/bcicen/slackcat/releases/download/v{{ slackcat.version }}/slackcat-{{ slackcat.version }}-linux-amd64"
    dest: /usr/local/bin/slackcat
    owner: root
    group: root
    mode: 0755

- name: Install z
  tags: [z, zsh]
  get_url:
    url: "https://raw.githubusercontent.com/rupa/z/{{ z.version }}/z.sh"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: Install base16-tomorrow-night
  tags: [base16-tomorrow-night, zsh]
  get_url:
    url: https://raw.githubusercontent.com/chriskempson/base16-shell/master/scripts/base16-tomorrow-night.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: Install base16-tomorrow
  tags: [base16-tomorrow, zsh]
  get_url:
    url: https://raw.githubusercontent.com/chriskempson/base16-shell/master/scripts/base16-tomorrow.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: Install ngrok
  tags: [ngrok]
  unarchive:
    src: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: /usr/local/bin
    remote_src: true

- name: Install nextcloud
  tags: [nextcloud]
  get_url:
    url: https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-{{nextcloud.version}}-x86_64.AppImage
    dest: /usr/local/bin/nextcloud
    owner: root
    group: root
    mode: 0755

- name: Install kvm
  tags: [kvm]
  apt:
    state: present
    update_cache: true
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager

- name: "Install kvm: add user to group"
  tags: [kvm]
  user:
    name: "{{ user.name }}"
    groups:
      - libvirt
      - libvirt-qemu
      - libvirt-dnsmasq
