# vim: set foldmethod=marker:
---
# Clone custom-oh-my-zsh {{{
- name: Ensure MyStuff directory exists
  tags: [zsh]
  file:
    path: ~/Development/MyStuff
    state: directory
- name: Clone custom-oh-my-zsh
  tags: [zsh]
  git:
    repo: git@github.com:jcmuller/custom-oh-my-zsh.git
    dest: ~/Development/MyStuff/custom-oh-my-zsh
    accept_hostkey: true
    update: true
# }}}
# Install yadm {{{
- name: Clone yadm
  tags: [yadm]
  git:
    repo: https://github.com/TheLocehiliosan/yadm.git
    dest: ~/.yadm-src
- name: Ensure bin exists
  tags: [yadm, dropbox, gopass]
  file:
    dest: ~/bin
    mode: 0755
    state: directory
- name: Install yadm
  tags: [yadm]
  file:
    src: ~/.yadm-src/yadm
    dest: ~/bin/yadm
    state: link
    mode: 0755
- name: Yadm get config
  command: ~/bin/yadm clone git@github.com:jcmuller/dotrcs.git
# }}}
# {{{ Install gopasspwd
- name: Copy gopasspwd
  tags: [gopass]
  copy:
    src: gopasspwd
    dest: ~/bin
    mode: 0755
# }}}
# {{{ Install antigen
- name: Antigen
  tags: [antigen, zsh]
  git:
    repo: https://github.com/zsh-users/antigen
    dest: ~/.antigen-src
# }}}
# Install dropbox {{{
- name: Install dropboxd
  tags: [dropbox]
  shell: wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
  args:
    chdir: ~/
    creates: ~/.dropbox-dist/dropboxd
- name: Install dropbox
  tags: [dropbox]
  get_url:
    url: https://www.dropbox.com/download?dl=packages/dropbox.py
    dest: ~/bin/dropbox
    mode: 0755
    force: true
# }}}
# Install browserpass-native {{{
- name: Build browserpass-native
  tags: [browserpass]
  make:
    target: configure
    chdir: ~/go/src/github.com/browserpass/browserpass-native
# }}}
- name: Install goobook # {{{
  tags: [mutt, goobook]
  pip:
    name: goobook
    executable: pip3
# }}}
- name: Install asdf #{{{
  tags: [asdf]
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: "{{ asdf.version}}"

- name: Install asdf plugins
  tags: [asdf, asdf-plugins]
  shell: |
    . ~/.asdf/asdf.sh
    asdf plugin add {{item.name}}
  args:
    executable: /bin/bash
    creates: "~/.asdf/plugins/{{item.name}}"
  with_items: "{{asdf.plugins}}"

- name: Install versions
  tags: [asdf, asdf-plugins]
  shell: |
    . ~/.asdf/asdf.sh
    asdf install {{item.name}} {{item.version}}
    asdf global {{item.name}} {{item.version}}
  args:
    executable: /bin/bash
    creates: "~/.asdf/installs/{{item.name}}/{{item.version}}"
  with_items: "{{asdf.plugins}}"
#}}}
# Helm plugins {{{
- name: Install helm plugins
  tags: [helm-plugins]
  shell: helm plugin install {{ item.source }} --version {{ item.version }}
  with_items: "{{ helm.plugins }}"
# }}}
